export const reminderCopy = {
  ru: {
    title: 'Напомнить мне',
    bell: 'Личное напоминание',
    subtitle: 'Telegram',
    connect: 'Подключить Telegram',
    open: 'Открыть Telegram',
    connected: 'Telegram подключён',
    disconnect: 'Отключить',
    disconnectConfirm: 'Отключить Telegram и отменить все свои напоминания?',
    cancel: 'Отмена',
    save: 'Сохранить',
    remove: 'Отменить напоминания',
    close: 'Закрыть',
    refresh: 'Обновить',
    before: 'За 30 минут',
    ownInterval: 'Свой интервал',
    amount: 'Количество',
    minutes: 'минут',
    hours: 'часов',
    days: 'дней',
    beforeDeadline: 'До дедлайна',
    afterDeadline: 'После дедлайна',
    add: 'Добавить время',
    offsetLimit: 'До 8 напоминаний: от 30 дней до дедлайна до 3 дней после.',
    intervalInvalid: 'Введи целое положительное число в допустимом диапазоне.',
    test: 'Тестовое уведомление',
    testQueued: 'Тест в очереди. Обычно приходит в течение минуты.',
    testWait:
      'Повторить тест можно через минуту, после завершения предыдущего.',
    testStatus: 'Проверка доставки',
    relativeMode: 'От дедлайна',
    exact: 'В срок',
    after: 'Через 30 минут',
    custom: 'Дата и время',
    note: 'Дополнительный текст',
    notePlaceholder: 'Необязательно',
    timezone: 'Часовой пояс',
    setup:
      'Telegram ещё не настроен. Владельцу сайта нужно подключить бота и планировщик.',
    scheduler:
      'Планировщик пока не подтвердил работу. Проверьте настройку Supabase Cron.',
    error: 'Не удалось выполнить запрос. Проверь подключение и попробуй снова.',
    invalid: 'Выбери время в будущем, не дальше двух лет.',
    changed: 'Карточка изменилась. Проверь дедлайн и выбранное время.',
    linkHint:
      'Открой бота и нажми Start. Ссылка одноразовая, действует 10 минут. Не пересылай её другим.',
    linkExpired: 'Ссылка истекла. Создай новую.',
    wait: 'Создать новую ссылку можно через 30 секунд.',
    privacy:
      'Только тебе. В Telegram отправятся название, проект, время и твой дополнительный текст, без описания карточки и картинок.',
    precision:
      'Отправка обычно в течение минуты. Уже отправленное сообщение отменить нельзя.',
    schedule: 'Мои напоминания',
    saved: 'Напоминание сохранено',
    deleted: 'Напоминания отменены',
    past: 'Уже прошло',
    done: 'Карточка выполнена',
    statuses: {
      pending: 'Запланировано',
      claimed: 'В очереди',
      sending: 'Отправляется',
      sent: 'Отправлено',
      failed: 'Не отправлено',
      unknown: 'Доставка не подтверждена',
      expired: 'Время пропущено',
      cancelled: 'Отменено',
    },
  },
  en: {
    title: 'Remind me',
    bell: 'Personal reminder',
    subtitle: 'Telegram',
    connect: 'Connect Telegram',
    open: 'Open Telegram',
    connected: 'Telegram connected',
    disconnect: 'Disconnect',
    disconnectConfirm: 'Disconnect Telegram and cancel all your reminders?',
    cancel: 'Cancel',
    save: 'Save',
    remove: 'Cancel reminders',
    close: 'Close',
    refresh: 'Refresh',
    before: '30 min before',
    ownInterval: 'Custom interval',
    amount: 'Amount',
    minutes: 'minutes',
    hours: 'hours',
    days: 'days',
    beforeDeadline: 'Before deadline',
    afterDeadline: 'After deadline',
    add: 'Add time',
    offsetLimit:
      'Up to 8 reminders: from 30 days before to 3 days after the deadline.',
    intervalInvalid:
      'Enter a positive whole number within the supported range.',
    test: 'Test notification',
    testQueued: 'Test queued. Usually arrives within one minute.',
    testWait:
      'Wait one minute and let the previous test finish before trying again.',
    testStatus: 'Delivery check',
    relativeMode: 'From deadline',
    exact: 'On time',
    after: '30 min after',
    custom: 'Date and time',
    note: 'Additional message',
    notePlaceholder: 'Optional',
    timezone: 'Time zone',
    setup:
      'Telegram is not configured yet. The site owner needs to connect the bot and scheduler.',
    scheduler:
      'The scheduler has not reported healthy yet. Check Supabase Cron setup.',
    error: 'Request failed. Check your connection and try again.',
    invalid: 'Choose a future time within two years.',
    changed: 'The card changed. Check the deadline and selected times.',
    linkHint:
      'Open the bot and press Start. This single-use link expires in 10 minutes. Do not share it.',
    linkExpired: 'The link expired. Create a new one.',
    wait: 'Wait 30 seconds before creating a new link.',
    privacy:
      'Only you. Telegram receives the title, project, time and your additional message, without the card description or images.',
    precision:
      'Usually sent within one minute. Already sent messages cannot be recalled.',
    schedule: 'My reminders',
    saved: 'Reminder saved',
    deleted: 'Reminders cancelled',
    past: 'Already passed',
    done: 'This card is completed',
    statuses: {
      pending: 'Scheduled',
      claimed: 'Queued',
      sending: 'Sending',
      sent: 'Sent',
      failed: 'Failed',
      unknown: 'Delivery unconfirmed',
      expired: 'Missed',
      cancelled: 'Cancelled',
    },
  },
}
